### ISSUE TITLE
Not work.

### ISSUE THREAD

**Issue by zw963** [plu5/smart-mode-line-powerline2#1]
theme file is in loadpath, but always following error.

``` cl
Debugger entered--Lisp error: (error "Unable to find theme file for `smart-mode-line-powerline2'")
  signal(error ("Unable to find theme file for `smart-mode-line-powerline2'"))
  error("Unable to find theme file for `%s'" smart-mode-line-powerline2)
  load-theme(smart-mode-line-powerline2 nil)
  sml/apply-theme(powerline2 nil :silent)
  sml/-setup-theme()
  sml/setup()
  eval((sml/setup) nil)
  eval-last-sexp-1(nil)
  eval-last-sexp(nil)
  call-interactively(eval-last-sexp nil nil)
```

**Comment by plu5** [comment]
perhaps try placing `smart-mode-line-powerline2-theme.el` in a folder that’s included in `custom-theme-load-path` by default, like `custom-theme-directory` (.../share/emacs/24.5/etc/themes/).
an excerpt from your initialisation file (.emacs) might shed light on the issue, though it does looks like you are loading everything in the correct order. should just be a matter of whether `custom-theme-load-path` is set before sml is setup unless I’ve overlooked something

**Comment by zw963** [comment]
Sorry, It work now.

I misunderstood about `custom-theme-load-path`  as the default emacs `load-path`.
